name: draggable_scrollbar
description: A scrollbar that can be dragged for quickly navigation through a vertical list.
             Additional option is showing label next to scrollthumb with information about current item.
version: 0.0.5
authors:
 - Flutter Community <community@flutter.zone>
 - Marina Kuznetsova <marica.tim@gmail.com>
 - Brian Egan <brian@brianegan.com>
homepage: https://github.com/fluttercommunity/flutter-draggable-scrollbar
maintainer: Marina Kuznetsova (@marica27)

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
